import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {FontAwesomeModule} from '@fortawesome/angular-fontawesome';
import {library} from '@fortawesome/fontawesome-svg-core';
import {fas} from '@fortawesome/free-solid-svg-icons';
import {AppRoutingModule} from '@src/app/app-routing.module';
import {AppComponent} from '@src/app/app.component';
import {HttpClientModule} from '@angular/common/http';
import {RouterModule} from '@angular/router';
import {CoreModule} from '@src/app/core/core.module';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {ModulesModule} from '@src/app/modules/modules.module';
import {ServiceWorkerModule} from '@angular/service-worker';
import {environment} from '@src/environments/environment';
import {ModalsModule} from '@src/app/shared/services/modals/modals-templates/modals.module';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

library.add(fas);

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    RouterModule,
    FontAwesomeModule,
    BrowserAnimationsModule,
    HttpClientModule,
    CoreModule,
    ModulesModule,
    ServiceWorkerModule.register('ngsw-worker.js', {enabled: environment.production}),
    ModalsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
